# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-16 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='lft',
            field=models.IntegerField(verbose_name='left Traversal'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='rght',
            field=models.IntegerField(verbose_name='right Traversal'),
        ),
    ]
